#!/usr/bin/env php
<?php
declare(strict_types=1);

function usage(): void {
    $msg = <<<TXT
Usage:
  php wccms/sql/tools/schema_diff_additive.php \
    --source /path/to/source_schema.sql \
    --target /path/to/target_schema.sql \
    --out /path/to/migration.sql

Generates additive migration SQL only:
- CREATE TABLE for tables missing in target
- ALTER TABLE ADD COLUMN for columns missing in target
No deletes/drops are generated.
TXT;
    fwrite(STDERR, $msg . PHP_EOL);
}

function parseArgs(array $argv): array {
    $opts = [
        'source' => null,
        'target' => null,
        'out' => null,
    ];

    for ($i = 1; $i < count($argv); $i++) {
        $arg = $argv[$i];
        if (str_starts_with($arg, '--source=')) {
            $opts['source'] = substr($arg, 9);
            continue;
        }
        if (str_starts_with($arg, '--target=')) {
            $opts['target'] = substr($arg, 9);
            continue;
        }
        if (str_starts_with($arg, '--out=')) {
            $opts['out'] = substr($arg, 6);
            continue;
        }

        if ($arg === '--source' && isset($argv[$i + 1])) {
            $opts['source'] = $argv[++$i];
            continue;
        }
        if ($arg === '--target' && isset($argv[$i + 1])) {
            $opts['target'] = $argv[++$i];
            continue;
        }
        if ($arg === '--out' && isset($argv[$i + 1])) {
            $opts['out'] = $argv[++$i];
            continue;
        }

        throw new RuntimeException("Unknown argument: {$arg}");
    }

    foreach (['source', 'target', 'out'] as $key) {
        if (!is_string($opts[$key]) || $opts[$key] === '') {
            throw new RuntimeException("Missing required argument --{$key}");
        }
    }

    return $opts;
}

function parseSchema(string $sql): array {
    $tables = [];
    $lines = preg_split('/\R/', $sql) ?: [];

    $collecting = false;
    $tableName = '';
    $stmtLines = [];

    foreach ($lines as $line) {
        if (!$collecting) {
            if (preg_match('/^\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?`?([A-Za-z0-9_]+)`?\s*\(/i', $line, $m)) {
                $collecting = true;
                $tableName = $m[1];
                $stmtLines = [$line];
            }
            continue;
        }

        $stmtLines[] = $line;
        if (preg_match('/^\)\s*ENGINE\s*=|^\)\s*;/i', trim($line))) {
            $statement = implode(PHP_EOL, $stmtLines) . PHP_EOL;
            $tables[$tableName] = [
                'statement' => $statement,
                'columns' => parseColumns($stmtLines),
            ];

            $collecting = false;
            $tableName = '';
            $stmtLines = [];
        }
    }

    return $tables;
}

function parseColumns(array $stmtLines): array {
    $columns = [];

    foreach ($stmtLines as $line) {
        $trim = trim($line);
        if ($trim === '' || $trim[0] === ')' || $trim[0] === '(') {
            continue;
        }

        if (preg_match('/^(PRIMARY|UNIQUE|KEY|INDEX|CONSTRAINT|FULLTEXT|SPATIAL|CHECK)\b/i', $trim)) {
            continue;
        }

        $normalized = rtrim($trim, ',');
        if (preg_match('/^`([^`]+)`\s+(.+)$/', $normalized, $m)) {
            $name = $m[1];
            $columns[$name] = "`{$name}` {$m[2]}";
            continue;
        }

        if (preg_match('/^([A-Za-z_][A-Za-z0-9_]*)\s+(.+)$/', $normalized, $m)) {
            $name = $m[1];
            $columns[$name] = "`{$name}` {$m[2]}";
        }
    }

    return $columns;
}

function buildAdditiveSql(array $sourceTables, array $targetTables): array {
    $out = [];
    $createdTables = 0;
    $addedColumns = 0;

    foreach ($sourceTables as $tableName => $sourceMeta) {
        if (!isset($targetTables[$tableName])) {
            $out[] = "-- Table missing in target: {$tableName}";
            $out[] = rtrim($sourceMeta['statement']);
            $out[] = '';
            $createdTables++;
            continue;
        }

        $targetColumns = $targetTables[$tableName]['columns'];
        foreach ($sourceMeta['columns'] as $columnName => $columnDef) {
            if (isset($targetColumns[$columnName])) {
                continue;
            }

            $out[] = "-- Column missing in target: {$tableName}.{$columnName}";
            $out[] = sprintf('ALTER TABLE `%s` ADD COLUMN %s;', $tableName, $columnDef);
            $out[] = '';
            $addedColumns++;
        }
    }

    array_unshift(
        $out,
        '-- Additive schema migration generated by schema_diff_additive.php',
        '-- Only CREATE TABLE and ADD COLUMN statements are included',
        '-- Review before applying',
        sprintf('-- Summary: %d table(s) to create, %d column(s) to add', $createdTables, $addedColumns),
        ''
    );

    return $out;
}

try {
    $args = parseArgs($argv);
} catch (Throwable $e) {
    usage();
    fwrite(STDERR, $e->getMessage() . PHP_EOL);
    exit(1);
}

$sourcePath = $args['source'];
$targetPath = $args['target'];
$outPath = $args['out'];

if (!is_file($sourcePath)) {
    fwrite(STDERR, "Source schema not found: {$sourcePath}" . PHP_EOL);
    exit(1);
}
if (!is_file($targetPath)) {
    fwrite(STDERR, "Target schema not found: {$targetPath}" . PHP_EOL);
    exit(1);
}

$sourceSql = (string) file_get_contents($sourcePath);
$targetSql = (string) file_get_contents($targetPath);

$sourceTables = parseSchema($sourceSql);
$targetTables = parseSchema($targetSql);

$lines = buildAdditiveSql($sourceTables, $targetTables);
$outSql = implode(PHP_EOL, $lines) . PHP_EOL;

$outDir = dirname($outPath);
if (!is_dir($outDir) && !mkdir($outDir, 0775, true) && !is_dir($outDir)) {
    fwrite(STDERR, "Unable to create output directory: {$outDir}" . PHP_EOL);
    exit(1);
}

if (file_put_contents($outPath, $outSql) === false) {
    fwrite(STDERR, "Unable to write output file: {$outPath}" . PHP_EOL);
    exit(1);
}

echo "Additive migration written to: {$outPath}" . PHP_EOL;
